name: learn-github-actions
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Fast action
        uses: BigMilts/FAST@FAST_ACTION2
       
